Repository dude613/Avoda2, pull requests merged in 2025-02, with the labels that each got.

#11 Chore: bring staging up to speed with main
  .github/workflows/staging.yml
  avoda-be/eslint.config.js
  avoda-be/pnpm-lock.yaml
  avoda-be/src/auth/auth.service.ts
  avoda-be/src/decorators/permissions.decorator.ts
  avoda-be/src/organizations/organizations.controller.ts
  avoda-be/src/organizations/organizations.service.ts
Labels: Review effort 4/5

#20 Feat/setup shadcn
  avoda-be/src/organizations/controllers/members.controller.ts
  avoda-fe/assets/css/main.css
  avoda-fe/assets/css/tailwind.css
  avoda-fe/components.json
  avoda-fe/components/Auth/Login.vue
  avoda-fe/components/Auth/Register.vue
  avoda-fe/components/ui/button/Button.vue
  avoda-fe/components/ui/button/index.ts
  avoda-fe/components/ui/toast/Toast.vue
  avoda-fe/components/ui/toast/ToastAction.vue
  avoda-fe/components/ui/toast/ToastClose.vue
  avoda-fe/components/ui/toast/ToastDescription.vue
  avoda-fe/components/ui/toast/ToastProvider.vue
  avoda-fe/components/ui/toast/ToastTitle.vue
  avoda-fe/components/ui/toast/ToastViewport.vue
  avoda-fe/components/ui/toast/Toaster.vue
  avoda-fe/components/ui/toast/index.ts
  avoda-fe/components/ui/toast/use-toast.ts
  avoda-fe/composables/useApi.composable.ts
  avoda-fe/composables/useTimer.composable.ts
  avoda-fe/lib/utils.ts
  avoda-fe/nuxt.config.ts
  avoda-fe/package.json
  avoda-fe/pages/Auth/Login.vue
  avoda-fe/pages/Auth/Register.vue
  avoda-fe/pnpm-lock.yaml
  avoda-fe/tailwind.config.js
  package-lock.json
  public/google-icon.png
Labels: Review effort 4/5

#21 fix: remove duplicate imports
  avoda-be/src/decorators/current-user.decorator.ts
  avoda-be/src/organizations/controllers/members.controller.ts
  package-lock.json
  public/google-icon.png
Labels: Review effort 1/5

#23 Hot fix/confirm password
  avoda-be/pnpm-lock.yaml
  avoda-be/src/auth/dto/create-user.dto.ts
Labels: Review effort 2/5

#24 Added Forgot Password page, updated layouts & middleware
  avoda-fe/components/AppHeader.vue
  avoda-fe/components/Auth/Login.vue
  avoda-fe/components/Auth/Register.vue
  avoda-fe/components/Auth/forgot-password.vue
  avoda-fe/layouts/auth.vue
  avoda-fe/middleware/auth.global.ts
  avoda-fe/pages/Auth/Login.vue
  avoda-fe/pages/Auth/Register.vue
  avoda-fe/pages/Auth/forgot-password.vue
  avoda-fe/pages/index.vue
  avoda-fe/pnpm-lock.yaml
Labels: Review effort 3/5

#32 Fix register validation
  avoda-fe/components/Auth/Login.vue
  avoda-fe/components/Auth/Register.vue
  avoda-fe/components/icons/google.vue
  avoda-fe/pages/Auth/Login.vue
  avoda-fe/pnpm-lock.yaml
Labels: Review effort 3/5

#35 Feat/profile
  avoda-fe/assets/css/tailwind.css
  avoda-fe/components.json
  avoda-fe/components/ui/card/Card.vue
  avoda-fe/components/ui/card/CardContent.vue
  avoda-fe/components/ui/card/CardDescription.vue
  avoda-fe/components/ui/card/CardFooter.vue
  avoda-fe/components/ui/card/CardHeader.vue
  avoda-fe/components/ui/card/CardTitle.vue
  avoda-fe/components/ui/card/index.ts
  avoda-fe/lib/utils.ts
  avoda-fe/pages/dashboard/profile.vue
Labels: Review effort 2/5

#37 Feat/profile
  avoda-fe/components/AppHeader.vue
  avoda-fe/components/ui/input/Input.vue
  avoda-fe/components/ui/input/index.ts
  avoda-fe/package.json
  avoda-fe/pages/dashboard/profile.vue
  avoda-fe/pnpm-lock.yaml
Labels: Review effort 2/5
